### PR TITLE
Update 04a-Vulnerability Scanning.md

### PR DESCRIPTION
**Pull request by resxar**
[Add] Adding an explanation about Vulnerability Scanning
[Add] Adding references
[Add] Adding the list of tools
[Modified] Tidy up the list of tools

### CODE REVIEW

**Comment by Ali-Yazdani** [comment]
Hi @resxar, 
What is your comment about adding container scanning here? Also, I was thinking about putting the web application scanner (like Burp suite) in the DAST file. 
@SudE29537 please drop your comment about container scanning.

**Comment by SudE29537** [comment]
I believe container scanning is a great addition.

**Comment by resxar** [comment]
Hi @Ali-Yazdani 
Container scanning sounds great, I thought it should be helpful to check whether the container contains a vulnerable library or not. Also, I agreed if you want to put the web application scanner such as Burp Suite, WPScan, etc In the DAST file.

And I was thinking to rename the file from `02a-Static scanning.md` to `02-Static_Applicatio_Security_Testing.md` and from `03a-Dynamic scanning.md` to `03a-Dynamic_Application_Security_Testing.md`. Is that okay?

**Comment by Ali-Yazdani** [comment]
@resxar Please solve the conflict.

**Comment by resxar** [comment]
Hi @Ali-Yazdani I think the conflict has been solved.

**Pull request merged**
