### PR TITLE
Add SCA

### PR DESCRIPTION
**Pull request by myugan**
Hi @Ali-Yazdani 

I made some changes for the markdown name especially each stage of the DevSecOps pipeline, I'm not sure this is a good thing or not by using numbers at the beginning of the markdown name. But we need to sort these as a common DevSecOps pipeline for example SCA or Secrets thing will be put at the beginning of pipelines and going forward to another security testing like SAST, DAST, IaC, etc. Or maybe we can remove the numbers for markdown, and we mentioned each stage of DevSecOps pipeline in `README.md` something like this:

```
This is a common DevSecOps methodology that should be embedded as part of the CI/CD pipeline:
1. SCA -> text is embedded by the link that refers to document/Component_Analysis.md
2. Secrets Management
3. SAST
4. DAST
5. IaC Scanning
6. Compliance
7. Vulnerability Management
etc.
```

What do you think about it? Then we don't need to care about restructure the document name

### CODE REVIEW

**Comment by Ali-Yazdani** [comment]
Hi @myugan,
These changes need to more discuss, let me keep the current structure, please assist to add more information then we can have a restructure for the future.

**Comment by Ali-Yazdani** [comment]
@myugan since we had a restructure please check your PR. you need to change some part of this.

**Comment by myugan** [comment]
Sure @Ali-Yazdani

**Comment by myugan** [comment]
Please check it @Ali-Yazdani

**Pull request merged**
