### PR TITLE
Update 04a-Vulnerability Scanning.md

### PR DESCRIPTION
**Pull request by SudE29537**
Updating the Vulnerability Scanner document

Added description and tools

### CODE REVIEW

**Comment by Ali-Yazdani** [comment]
Hi @SudE29537 ,
Could you please add some information about why we need VS in the DevSecOps process?

**Comment by SudE29537** [comment]
Will do

**Comment by SudE29537** [comment]
Just added some info. If you believe we need more, just let me know

**Comment by Ali-Yazdani** [comment]
It's would be better than we have more information about this part. but let me merge your PR then you can add more info the next time.

**Comment by SudE29537** [comment]
I'll work on this and submit it again soon.

**Pull request merged**
